version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: echo $CONFIG > config.json
      - run: git config user.email "dev.linxu@gmail.com"
      - run: git config user.name "Luke Lin"
      - run: git pull
      - run: sudo pip3 install -r req.txt
      - run: python3 leetcode_generate.py

workflows:
  test-env-vars:
    jobs:
      - build:
          context: Leetcode_Context
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "30 11 * * *"
          filters:
            branches:
              only: dev_luke

    jobs:
      - build:
        context: Leetcode_Context
